---
creation_rules:
  - path_regex: /*.tfvars
    age: age1s90xwvtqw9at892s8tyde9lp8vu3rs2lde7pwh7hayuc2sahmv6qmkwpff
    format: ini
    input_type: ini
  - path_regex: ./.*/*.json
    age: age1s90xwvtqw9at892s8tyde9lp8vu3rs2lde7pwh7hayuc2sahmv6qmkwpff

stores:
  yaml:
    indent: 2
  json:
    indent: 2
